# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'numberTwo.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import pkg_resources
pkg_resources.require("pandas==1.1.3")
import pandas as pd
pkg_resources.require("xlrd==1.2.0")
import xlrd

from PyQt5.QtWidgets import QApplication
import pyqtgraph as pg
from pyqtgraph import PlotWidget


from PyQt5 import QtCore, QtGui, QtWidgets
from  PyQt5.QtWidgets  import *
from  PyQt5.uic  import  loadUi

from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg, NavigationToolbar2QT as NavigationToolbar
import  numpy  as  np
import  random
from itertools import count
import pandas as pd
import numpy as np

import time
import math

flag=True
x=0

data_set1 = pd.read_csv("ecg1.csv")
yb = data_set1.iloc[:, 1].values
xa = data_set1.iloc[:, 0].values
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 30, 5810, 3910))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(210, 480, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton2.setGeometry(QtCore.QRect(400, 480, 75, 23))
        self.pushButton2.setObjectName("pushButton2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.graphicsView = pg.PlotWidget(self.verticalLayoutWidget)
        self.graphicsView.setGeometry(5,5,800,500)
        self.pushButton.clicked.connect(self.start)
        self.pushButton2.clicked.connect(self.start2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.pushButton2.setText(_translate("MainWindow", "PushButton2"))

    def start(self):
        x=np.arange(1000)
        y=2*x

        self.graphicsView.plot(xa, yb, pen=pg.mkPen('b', width=1))


    def start2(self):
        plt.close()
        fig, ax = plt.subplots()
        global x
        x=0
        global flag
        flag =True
        data_set1= pd.read_csv('ecg1.csv')
        yb=data_set1.iloc[:,1].values
        print("Hello")
        def animate(i):
            global x
            global flag
            if not flag:
                self.ani.event_source.stop()
            else:

                x=i
                data_set1= pd.read_csv('ecg1.csv')
                xa=data_set1.iloc[2*int(((i-100)+abs(i-100))/2):2*i,0].values
                y1=data_set1.iloc[2*int(((i-100)+abs(i-100))/2):2*i,1].values
                plt.cla()
                axes = plt.gca()
                axes.set_ylim([min(yb),max(yb)])
                axes.plot(xa, y1, label='Channel 1')
                plt.legend(loc='upper left')
                plt.tight_layout()
        self.graphicsView.plot(xa, yb, pen=pg.mkPen('b', width=1))
        self.ani = FuncAnimation(plt.gcf(), animate, interval=0.001)
        plt.tight_layout()




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
